[package]
name = "crab_sh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shellexpand = "2.1"
dirs = "4.0"
log = "0.4.0"
env_logger = "0.9.1"

[dev-dependencies]
pretty_assertions = "1"
