[package]
name = "crab_sh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shellexpand = "3.1"
dirs = "6.0"
log = "0.4.28"
env_logger = "0.11.8"

[dev-dependencies]
pretty_assertions = "1"
